package io.yahorbarkouski.notion.toggler.gradle.generator

import io.yahorbarkouski.notion.toggler.core.FeatureFlag
import java.io.File

abstract class FeatureGenerator {

    abstract fun generate(
        features: List<FeatureFlag>,
        packageName: String,
        projectDirectory: File
    )

    companion object {
        const val FILE_HEADER_KDOC =
            "CLASS IS GENERATED BY THE NOTION CODEGEN GRADLE PLUGIN. DO NOT EDIT."
    }
}
